version: "3.8"

services:
  frontend:
    build:
      context: ../Inventory-App-UI
    image: inventory-app-frontend:test
    ports:
      - "3100:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
    image: inventory-app-backend:test
    ports:
      - "8181:8080"
    restart: always
# Run:
# docker compose -f compose.test.yml -p inventory-app-test up -d --build
# Stop:
# docker compose -f compose.test.yml -p inventory-app-test down --volumes --rmi all
