services:
  frontend:
    build:
      context: ../Inventory-App-UI
    image: inventory-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
    image: inventory-app-backend
    network_mode: host
    restart: always
