services:
  frontend:
    build:
      context: ../Inventory-App-UI
    image: inventory-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
    image: inventory-app-backend
    ports:
      - "8080:8080"
    network_mode: host
    restart: always
# Run:
# docker compose -f compose.prod.yml -p inventory-app-prod up -d --build
# Stop:
# docker compose -f compose.prod.yml -p inventory-app-prod down --volumes --rmi all
