services:
  frontend:
    build:
      context: ../Inventory-App-UI
      args:
        ENV_FILE: .env
    image: inventory-app-frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    env_file:
      - ../Inventory-App-UI/.env
    environment:
      - PORT=3000

  backend:
    build:
      context: .
    image: inventory-app-backend-prod
    ports:
      - "8080:8080"
    network_mode: host
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8080
# Run:
# docker compose -f compose.prod.yaml -p inventory-app-prod up -d --build
# Stop:
# docker compose -f compose.prod.yaml -p inventory-app-prod down --rmi all
